import '../scss/style.scss'
import './swipper/swipper'
import './popupFeedback/popupFeedback.js'
import './popupCall/popupCall.js'
import './brandList/brandList'
import './serviceList/serviceList.js'
import './sidebar/sidebar.js'
